---
layout: post
title: Sermon and Pastoral Prayer
date: '2006-01-11T15:00:00.000-06:00'
author: Jabell
tags:
- Prayer
- Sermon
modified_time: '2007-03-31T18:43:25.029-05:00'
blogger_id: tag:blogger.com,1999:blog-19739956.post-113701438890886739
blogger_orig_url: http://theabellsix.blogspot.com/2006/01/sermon-and-pastoral-prayer.html
---

As I mentioned in the last post, here is a link to the sermon from last <a=http://www.desiringgod.org/library/sermons/06/010806.html>Sunday</a>.  It is well worth the read.<br /><br />Before Pastor Piper preached, our Lead Pastor for Life Training prayed over the entire church.  The following is his pastoral prayer:<br /><blockquote>I thank you for these people because of the grace given to them in Christ Jesus.  If there's one thing we need, it's enabling grace and you are giving it!<br /><br />When they don't feel steadfast, immovable, always abounding in the work of the Lord, help them know their labor in you is not in vain.<br /><br />I pray that you would keep them strong to the end, so that they will be blameless on the day of our Lord Jesus Christ.  You are faithful.<br /><br />Moses prayed that his people would have something to drink, so this morning I want to ask you to slake this people's thirst for you.<br /><br />Samuel cried out to you on behalf of his people and you thundered against the Philistines, and this morning I want to cry out to you to rescue this people from deeply entrenched habits, untruthful self-talk, accomodation and double-mindedness in world view, wrongful appetites, selfishness, pornography, and our own foolishness.<br /><br />Elijah prayed and you answered so the people would know that you, O Lord, are God and that you are turning their hearts back again, and this morning I want to ask you to grant the gift of faith so that this people would know that you are, and that you are a rewarder of those who diligently seek you.<br /><br />I feel badly that some here are facing physical pain and deadly diseases.  Some encounter great doubts of the soul and demonic oppression.  Others are experiencing confusion, perplexity and darkness.  There are strained and estranged relationships that ache.  This people faces a sea of misery in this fallen world.<br /><br />Great Shepherd of the sheep, would you grant comfort and hope to those who need it.  Give a mighty break through to those who need it.  Give a swift kick in the pants to those of us who would profit from that.  Put your arm around the lonely.  And work all things together for the good of those who love you, those who are the called according to your purpose, and conform them to the image of your son in whose name I pray.<br /><br />Amen.</blockquote>