---
layout: post
title: Winter's Almost Over
date: '2006-03-03T12:14:00.000-06:00'
author: Wendy
tags:
- Family
- Weather
modified_time: '2007-03-31T18:36:51.525-05:00'
blogger_id: tag:blogger.com,1999:blog-19739956.post-114141041617426089
blogger_orig_url: http://theabellsix.blogspot.com/2006/03/winters-almost-over.html
---

Minnesota has a reputation for being cold in the winters.  While there have been a few days this winter where the temperatures dipped below zero, the vast majority has been disappointing.  After all, if you are going to live in a winter climate, it would be nice to actually have the climate live up to it's reputation.<br /><br /><a href="http://photos1.blogger.com/blogger/6192/1973/1600/IMG_4372.0.jpg"><img style="margin: 0pt 10px 10px 0pt; float: left; cursor: pointer;" src="http://photos1.blogger.com/blogger/6192/1973/320/IMG_4372.0.jpg" alt="" border="0" /></a><br /><br />Despite the poor showing of old man winter this year, there was still enough snow on the slopes for Chase to do his impression of Shaun White, the Flying Tomato.  Clearly, Chase has been inspired by the Olympics.<br /><a href="http://photos1.blogger.com/blogger/6192/1973/1600/IMG_4357.0.jpg"><img style="margin: 0pt 10px 10px 0pt; float: left; cursor: pointer;" src="http://photos1.blogger.com/blogger/6192/1973/320/IMG_4357.0.jpg" alt="" border="0" /></a><br /><br />While Chase is bent on being the next snowboarding superstar, Mackenzie is taking things a bit more on the ground.  She is carefully making her way down the hill.<br /><a href="http://photos1.blogger.com/blogger/6192/1973/1600/100_0988.0.jpg"><img style="margin: 0pt 10px 10px 0pt; float: left; cursor: pointer;" src="http://photos1.blogger.com/blogger/6192/1973/320/100_0988.0.jpg" alt="" border="0" /></a><br /><br />Kayleigh doesn't care much for snowboarding.  She would rather sled down the hill and is quite the daredevil.  However, it can get boring quickly, so she takes a time out on the swings.<br /><a href="http://photos1.blogger.com/blogger/6192/1973/1600/100_1008.jpg"><img style="margin: 0pt 10px 10px 0pt; float: left; cursor: pointer;" src="http://photos1.blogger.com/blogger/6192/1973/320/100_1008.jpg" alt="" border="0" /></a><br /><br />Brooklyn and Avery share a moment in the snow.<br /><br />We had a good time sledding and snowboarding while our friends were here, among other things.  It was good to hang out, much like old times.  Last weekend, Brooklyn and Claire celebrated their birthdays together, and we all had a fun day together!<br /><br />Our friends left last Monday, so we simply tried to get back to normal this week.  Jason taught two classes on Wednesday night, Arcing and Diagramming, and Theological Foundations.  He is really busy right now with his Romans 9-11 class, and a seminar on TULIP.<br /><br />The kids and I have been doing school and playing around the house.