---
layout: post
title: Just Showed Up For My Own Life
date: '2007-05-18T23:24:00.000-05:00'
author: Jabell
tags:
- Music
- Justice
- Movies
modified_time: '2007-05-18T23:39:50.074-05:00'
blogger_id: tag:blogger.com,1999:blog-19739956.post-6472204216615389772
blogger_orig_url: http://theabellsix.blogspot.com/2007/05/just-showed-up-for-my-own-life.html
---

Our church hosts what they call “First Friday Films,” which happens (usually) on the first Friday of every month.  A documentary film with a global message is typically shown and then discussed from a Christian standpoint.  This gives people who attend the opportunity to see things outside their bubble and then discuss global issues within a gospel context.<br /><br />Tonight (obviously not a first Friday) <a href="http://www.skyhousefilms.com/Home.html">John Gyovai</a>, president of MediaServe International, a non-profit ministry birthed at Bethlehem, hosted a <a href="http://www.nomadshow.com/index.html">Nomad Show</a> movie based on <a href="http://www.saragroves.com/">Sara Groves</a><a href="http://www.saragroves.com/">’</a> trips to Louisiana and Rwanda.  <a href="http://www.nomadshow.com/sgtrailer.html">"Just Showed Up For My Own Life</a><a href="http://www.nomadshow.com/sgtrailer.html">"</a> documents her trip to Louisiana (for Katrina relief efforts), and her trip to Rwanda.  Both of these experiences expanded her learning about the world and to allowed her to be impacted by the horror of the genocide that took place there in 1994.  The trip to Rwanda also connected Sara with <a href="http://www.ijm.org">Gary Haugen of International Justice Mission.</a><br /><br />Wendy and I have been fans of Sara Groves for years and own all of her CDs.  Sara, who lives in Minneapolis was at the screening and spent time answering questions.  Our kids were able to talk with her and get her autograph.  Her last album, which found its culmination in these trips was titled, “Add to the Beauty.”  Her point is that as Christians, we should be adding to the beauty in this world as we are salt and light.<br /><br />Our goal tonight was not simply to promote another musician to the kids, but for them to see that whatever we do in life, it should have a gospel purpose.  This life is not about us, it is about God, and if that means delivering a tour bus full of diapers to a church in Louisiana or traveling with Gary Haugen of IJM to Rwanda, then to God be the glory.  Or, if it means picking up your family and moving to the mid-west to learn the Word of God in order to fulfill a calling to preach, then to God be the glory.<br /><br />Again, we are thankful for the opportunities that God has given us here in Minneapolis, often through <a href="http://www.hopeingod.org">Bethlehem</a>, to open our kids’ eyes to more than the Disneyland of America has to offer.