---
layout: post
title: Help me, O Lord!
date: '2008-04-05T10:44:00.004-05:00'
author: Jabell
tags:
- Sovereignty
- Christian Living
- Suffering
modified_time: '2008-08-25T10:05:46.907-05:00'
blogger_id: tag:blogger.com,1999:blog-19739956.post-6254482796089622838
blogger_orig_url: http://theabellsix.blogspot.com/2008/04/help-me-o-lord.html
---

The first eleven verses of Psalm 74 are a cry out to the Lord for help.  The “enemy” of the Lord, the Lord’s “foes” are destroying the meeting places of God.  They are breaking down the carved wood, they are setting the sanctuary on fire.  In the beginning of this psalm, Asaph sees this as God’s anger toward his people.  He attributes the suffering of God’s people at the hand of the Lord’s enemies as the Lord’s anger at his people, “O God, why do you cast us off forever?  Why does your anger smoke against the sheep of your pasture?”  This is a pleading cry, not an angry accusation.  Asaph understands that God is ultimately sovereign over the enemies.<br /><br />There is an interesting word at the beginning of verse 12.  In the ESV and NASB the word is “Yet.”  In the Hebrew it is a waw used in a concessive manner.  Despite the fact that God is angry toward us, <span style="font-style: italic;">nevertheless</span>, “God my King is from of old, working salvation in the midst of the earth.”<br /><br />This is an intriguing response to the situation that the people of God were in.   Asaph and the people of God are suffering.  They are being put down by God’s foes and enemies.  They are crying out to God for help, for defense, for deliverance.  Yet in the midst of this horror, Asaph recognizes, remembers, believes, holds-on to the fact that God is making salvation or working salvation from ancient times in the land.  God is doing something bigger in the midst of the terror.  God is working salvation in the land, despite the fact that everyone is at a loss.  God is doing something deeper than what Asaph and people see.  He is working salvation.<br /><br />Asaph then spends several verses (13-17) extolling the sovereignty of God over the earth, clearly describing again the power of God over all things, which is the basis of his belief in verse 12.  Then, from v. 18 to the end of the psalm Asaph returns to his pleas for salvation from God.  Verses 12-17 are the ground for Asaph’s pleas to God for deliverance both in the beginning and in the end of the Psalm.   Without that middle section, Asaph has no real basis for crying out to God.  It is the fact that God is sovereign over everything - the sea, the sea monsters, the springs and brooks, the day, the night, the stars, the sun, the boundaries of the earth and its seasons - that enables Asaph to confidently cry out to the Lord for help.<br /><br />O that I would believe and trust in the sovereignty of God the way that Asaph did.  O that I would cry out to my God, my king who is ancient of days, with the sheer confidence in his sovereignty for his deliverance of me from my troubles.