---
layout: post
title: The Greatest Story
date: '2009-08-07T08:37:00.006-05:00'
author: Jabell
tags:
- Affections
- Quotes
- Story
- Movies
modified_time: '2009-08-08T12:21:44.936-05:00'
blogger_id: tag:blogger.com,1999:blog-19739956.post-4178707613712634536
blogger_orig_url: http://theabellsix.blogspot.com/2009/08/greatest-story.html
---

I grew up escaping life into fiction. I went through a comic book phase, but mostly I read plain old escapist fiction. Starting in 3rd grade I read Narnia over and over. I read all that Jim Kjelgaard wrote in 5th and 6th grade, and The Three Investigators series in 7th and 8th grade. I read everything Louis L'Amour wrote in 9th grade, and then moved into science fiction and fantasy through 10th and 11th grade. The standout during those years were <span style="font-style: italic;">The Amber Chronicles;</span> 1,200 pages of pure bliss (well, at least the first 600, the last half weren't quite as good). I read <span style="font-style: italic;">The Bourne Identity</span> in my senior year, and then moved on to everything Tom Clancy. I was voracious.<br /><br />My French teacher in High School was exasperated with me for reading escapist fiction rather than good literature. I was okay with that at the time, though now I am trying to catch up and read the good stuff.<br /><br />I also loved movies. But not any movies, big action flicks where the hero was really good and he saved the girl in the end. My favorite all-time movie is <span style="font-style: italic;">Raiders of the Lost Ark</span>. I have seen most every block-buster since Indianna Jones hit the big screen in 1980 (with the proud exceptions of <span style="font-style: italic;">Dances with Wolves</span>, <span style="font-style: italic;">Forrest Gump</span>, and <span style="font-style: italic;">Titanic</span>).<br /><br />So? I love stories. I am drawn to stories. I am addicted to stories. Why? That is a good question. I have been thinking about why I in particular, and humans in general, like stories so much. That is why there have been so many posts on literature and story lately.<br /><br />Yesterday I quoted <a href="http://www.andrew-peterson.com/">Andrew Peterson</a>. Here is another quote that I think speaks to what I am talking about:<br /><blockquote>As I said, I grew up in the church. I went to Sunday school, VBS, church camp, Wednesday night Bible study—the whole shebang. But it wasn’t until my freshman year of Bible college, in an Old Testament survey class, that the light bulb finally went on. It was the first time I realized the Bible is telling one big story, and that story is the one God is telling with history. My love of fiction, of film, even of comic books began to make sense through that lens. What I had always loved about those stories was the Story, seen in glimpses, felt with goosebumps and lumps in the throat that I couldn’t explain. G.K. Chesterton said no man ever entered a brothel who wasn’t looking for God. Well, no one ever walked into a movie theater or read a novel who wasn’t hungry for the Gospel.</blockquote>I, too, love the greatest story the most.<br /><br />(HT: <a href="http://feedproxy.google.com/%7Er/BetweenTwoWorlds/%7E3/iNdYIDnHx84/interview-with-andrew-peterson-part-iii.html">Between Two Worlds</a>)