---
layout: post
title: 'Millennial Views in a Statement of Faith: Sin.'
date: '2009-07-14T10:47:00.003-05:00'
author: Jabell
tags:
- Bible
- Church
- Sin
modified_time: '2009-07-14T11:01:13.549-05:00'
blogger_id: tag:blogger.com,1999:blog-19739956.post-1821326562500422094
blogger_orig_url: http://theabellsix.blogspot.com/2009/07/millennial-views-in-statement-of-faith.html
---

<a href="http://feedproxy.google.com/%7Er/BetweenTwoWorlds/%7E3/5KyIyvTUEL8/dever-you-are-in-sin-if-you-lead-your.html">Justin Taylor</a> quotes Mark Dever saying that having a millennial view written into a church's statement of faith is sin. Having experienced this sort of thing first hand, I find Dever's quote refreshing. I agree with Dever and believe that a long-term consequence of this sin is a severe danger to the health of the church, since it breeds an "us vs. them" mentality. It certainly divides more than it unifies.<br /><blockquote>I think that millennial views need not be among those doctrines that divide us. . . . I am suggesting that what you believe about the millennium—how you interpret these thousand years—is not something that it is necessary for us to agree upon in order to have a congregation together. The Lord Jesus Christ prayed in John 17:21 that we Christians might be one. Of course all true Christians are one in that we have his Spirit, we share his Spirit, we desire to live out that unity. But that unity is supposed to be evident as a testimony to the world around us. Therefore, I conclude that we should end our cooperations together with other Christians (whether near-ly in a congregation, or more at length in working together in missions and church planting and evangelism and building up the ministry) only with the greatest of care, lest we rend the body of Christ for whose unity he’s prayed and given himself. Therefore, I conclude that it is sin to divide the body of Christ—to divide the body that he prayed would be united. Therefore for us to conclude that we must agree upon a certain view of alcohol, or a certain view of schooling, or a certain view of meat sacrificed to idols, or a certain view of the millennium in order to have fellowship together is, I think, not only unnecessary for the body of Christ, but it is therefore both unwarranted and therefore condemned by scripture. So if you’re a pastor and you’re listening to me, you understand me correctly if you think I’m saying you are in sin if you lead your congregation to have a statement of faith that requires a particular millennial view. I do not understand why that has to be a matter of uniformity in order to have Christian unity in a local congregation.</blockquote>Read Justin's entire <a href="http://feedproxy.google.com/%7Er/BetweenTwoWorlds/%7E3/5KyIyvTUEL8/dever-you-are-in-sin-if-you-lead-your.html">post</a> to find links to sermons by Mark Dever and Tom Schreiner, as well as an article by Sam Storms on the problems with the Premillennial view.