---
layout: post
title: What I am made for
date: '2009-12-02T08:40:00.004-06:00'
author: Jabell
tags:
- Thessalonians
- Teaching
modified_time: '2009-12-02T09:06:07.160-06:00'
blogger_id: tag:blogger.com,1999:blog-19739956.post-8103593239668230567
blogger_orig_url: http://theabellsix.blogspot.com/2009/12/what-i-am-made-for.html
---

I often think that I am schizophrenic when it comes to my career. We moved to Minneapolis believing that I was called to teach and preach the Word of God. Over the last five years that calling has been challenged as I struggled with studies and work and family. I really struggled creating new categories in my brain and learning the tools to study God's word well. I sinned by comparing myself to those who had more knowledge or learned faster or better. I am oh so slow and weak.<br /><br />At times, I doubted my call. I figured that this was all a mistake. Should I go back to engineering?<br /><br />This morning, as I am finishing my preparation for teaching Thessalonians tonight God gave me an insight, I think. I am inherently lazy. I was accused in college of "flying by the seat of my pants." I will happily do the least amount possible to accomplish a goal. So, when I am at the bottom of a hill looking up at a mountain of work, I would rather not climb the mountain.<br /><br />But, this morning, after working for two days to climb the mountain of 1 Thessalonians 5:1-11, I realized that the view from the top of the mountain is glorious. And I don't simply mean glorious, I mean <span style="font-style: italic;">really</span> glorious. Mind-blowingly beautiful. Heart-wrenching, tear-producing, glorious truth. Truth and beauty and glory that must be shared, that must be proclaimed.<br /><br />At this moment, sitting atop the mountain, I realize, I think, that this is what I am made for. Not simply to stand at the top of the mountain, but to share the view. To help other people see what I see. To proclaim, to plead, to describe, to exalt over, to exult in, and to display the view to the best of my ability.<br /><br />My problem is the mountain. Tomorrow, after I have shared the view with the few people who will listen, I will come down the mountain. I will be tired and worn out and think, man, that was hard work. I will not want to do the hard work again. I will dread next week when I have to climb again.<br /><br />Oh, how easily I forget the glorious view at the top. So, on one hand I believe that I am made to proclaim the view. But on the other hand, I do not delight in the hard work necessary to get to the top.<br /><br />Therefore, I waffle around in the valley, wondering what my career should be and what I was called to Minneapolis for.