---
layout: post
title: Dogmatics is...
date: '2010-02-23T22:55:00.004-06:00'
author: Jabell
tags:
- Theology
- Quotes
modified_time: '2010-02-23T23:28:19.365-06:00'
blogger_id: tag:blogger.com,1999:blog-19739956.post-1212730028846962173
blogger_orig_url: http://theabellsix.blogspot.com/2010/02/dogmatics-is.html
---

My Friend <a href="http://preciseandtowering.tumblr.com/post/389290364/god-always-god-from-beginning-to-end">posted</a> what he considers to be the “best definition of theology I’ve ever read.” Here is the full quote:<br /><blockquote>“Dogmatics is the system of the knowledge of God as he has revealed himself in Christ; it is the system of the Christian religion. And the essence of the Christian religion consists in the reality that the creation of the Father, ruined by sin, is restored in the death of the Son of God and re-created by the grace of the Holy Spirit into a kingdom of God. Dogmatics shows us how God, who is all-sufficient in himself, nevertheless glorifies himself in his creation, which, even when it is torn apart by sin, is gathered up again in  Christ (Eph. 1:10). It describes for us God, always God, from beginning to end—God in his being, God in his creation, God against sin, God in Christ, God breaking down all resistance through the Holy Spirit and guiding the whole of creation back to the objective he decreed for it: the glory of his name. Dogmatics, therefore, is not a dull and arid science. It is a theodicy, a doxology to all God’s virtues and perfections, a hymn of adoration and thanksgiving, a ‘glory to God in the highest’ (Luke 2:14).”<br /><br />[Herman Bavinck, <i>Reformed Dogmatics</i>, I.112, in the best definition of theology I’ve ever read (no offense to my hero Dr Webster)]<p></p></blockquote><p>Now, as you know, I am not nearly as sharp as the dullest tack in the box, so I had to look up a few words, scratch my head, scrunch up my eyes, and think real hard. For some reason, I can’t remember the definition of <span style="font-style: italic;">theodicy</span> to save my life. I have to look it up every time. (Rabbit trail: I really like the Command-Control-D sequence in a true Cocoa app; the instant dictionary rocks.)</p><p>According to the Oxford American Dictionary, Theodicy means, “the vindication of divine goodness and providence in view of the existence of evil.” Now, I don't know if that is what Herman Bavinck thought it meant, but when I put Bavinck's last sentence together with that definition, it goes like this:</p><p>“[Dogmatics] is a vindication of divine goodness and providence in view of the existence of evil, a doxology to all God’s virtues and perfections, a hymn of adoration and thanksgiving, a ‘glory to God in the highest’ (Luke 2:14).”</p><p>I like that. I think that makes sense.<br /></p>