---
layout: post
title: Capital “F” Friends
date: '2010-02-20T19:56:00.002-06:00'
author: Jabell
tags:
- Affections
- Friendship
modified_time: '2010-02-20T20:25:02.728-06:00'
blogger_id: tag:blogger.com,1999:blog-19739956.post-1643022214186937862
blogger_orig_url: http://theabellsix.blogspot.com/2010/02/capital-f-friends.html
---

A friend of mine <a href="http://preciseandtowering.tumblr.com/post/394759252/friendship-from-a-working-library">reposted</a> a quote regarding friendship, Facebook, and technology. The gist is that technology should not attempt to represent friendships. The purpose in this present post is not to debate that subject. After all, I don’t have a Facebook account; who am I to criticize?<br /><br />Rather, I am merely using this as a segue into a sappy post about friends. The following is not original, but I think it is accurate. I lament the lack of deep friendships in life. When I look around, I see people who have huge numbers of so-called friends, but very few <span style="font-style: italic;">deep</span> friends. In other words, there are friends with a little “f” and friends with a capital “F.” The first is a large group with sloppy admission standards, the other an elite, time-tested crew.<br /><br />What is the difference?<br /><br />A little “f” friend identifies themselves when they call.<br />A capital “F” Friend doesn’t have to.<br /><br />A little “f” friend opens a conversation with a full news bulletin on their life.<br />A capital “F” Friend says, “What’s new with you?”<br /><br />A little “f” friend thinks the problems you whine about are recent.<br />A capital “F” Friend says, “You’ve been whining about the same thing for 14 years. Get off your duff and do something about it.”<br /><br />A little “f” friend has never seen you cry.<br />A capital “F” Friend has shoulders soggy from your tears.<br /><br />A little “f” friend knows almost nothing about your family.<br />A capital “F” Friend knows the medical history, dietary habits and marital troubles of everyone on your tree.<br /><br />A little “f” friend calls you at 10 p.m. just to chat.<br />A capital “F” Friend knows you hate to be called after 9 p.m.<br /><br />A little “f” friend wonders about your romantic history.<br />A capital “F” Friend could blackmail you with it.<br /><br />A little “f” friend when visiting, they act like a guest.<br />A capital “F” Friend when visiting, they open your refrigerator, put they’re feet on the sofa, talk back to your spouse and reprimand your children.<br /><br />A little “f” friend thinks the friendship is over when you argue.<br />A capital “F” Friend knows that a friendship’s not a friendship until you’ve had a fight.