---
layout: post
title: Books Read
date: '2010-12-08T05:00:00.004-06:00'
author: Jabell
tags:
- Lists
- Books
modified_time: '2010-12-08T05:00:14.017-06:00'
blogger_id: tag:blogger.com,1999:blog-19739956.post-8583132163935580357
blogger_orig_url: http://theabellsix.blogspot.com/2010/12/books-read.html
---

I know of a prominent Christian pastor/speaker/blogger/writer that has been reading about one book per week for decades. The wife of one of my pastors set a goal this year to read 52 books, again the one book a week thing.<div><br /></div><div>I, however, set my sights a bit lower. The old cliché says to aim for the moon, and you will at least hit a star. I just went for the stars immediately.</div><div><br /></div><div>With the dawn of 2008 I determined to try and finish a minimum of 12 books a year, or a measly one book per month. Mostly, I have accomplished this. Here are my lists of finished books for 2008 and 2009.</div><div><br /></div><div><b>Books completed in 2008</b></div><div><br /></div><div><div><i>That Hideous Strength</i>, by C. S. Lewis</div><div><i>The Abolition of Man</i>, by C. S. Lewis</div><div><i>The Count of Monte Cristo</i>, by Alexandre Dumas</div><div><i>The Chronicles of Amber</i>, Volume 1, by Roger Zelazny</div><div><i>The Chronicles of Amber</i>, Volume 2, by Roger Zelazny</div><div><i>Trumps of Doom</i>, by Roger Zelazny</div><div><i>Blood of Amber</i>, by Roger Zelazny</div><div><i>Sign of Chaos</i>, by Roger Zelazny</div><div><i>Knight of Shadows</i>, by Roger Zelazny</div><div><i>Prince of Chaos</i>, by Roger Zelazny</div><div><i>Recalling the Hope of Glory</i>, by Allen P. Ross</div><div><i>Don't Make Me Think: A Common Sense Approach to Web Usability</i>, by Steve Krug</div><div><i>Thinking with Type: A Critical Guide</i>, by Ellen Lupton</div></div><div><br /></div><div><b>Books completed in 2009</b></div><div><br /></div><div><div><i>The Hobbit</i>, by J. R. R. Tolkein</div><div><i>The Brothers Karamazov</i>, by Fyodor Dostoevsky</div><div><i>100 Cupboards</i>, by N. D. Wilson</div><div><i>Dandelion Fire</i>, by N. D. Wilson</div><div><i>The Fellowship of the Ring</i>, by J. R. R. Tolkien</div><div><i>On Stories and Other Essays on Literature</i>, by C. S. Lewis</div><div><i>The Three Signs of a Miserable Job</i>, by Patrick Lencioni</div><div><i>Pride and Prejudice</i>, by Jane Austin</div><div><i>Notes from the Tilt-a-Whirl: Wide-Eyed Wonder in God’s Spoken World</i>, by N. D. Wilson</div><div><i>The Key-Lock Man</i>, by Louis L’Amour</div><div><i>The Two Towers</i>, by J. R. R. Tolkien</div></div><div><br /></div><div>2010 has been a much more successful year in terms of total books read, but who’s counting? I will post that list in early January, since I am still reading.</div><div><br /></div>