---
layout: post
title: Engineering or Humanities?
date: '2011-02-11T15:07:00.000-06:00'
author: Jabell
tags:
- School
modified_time: '2011-02-11T15:07:37.863-06:00'
blogger_id: tag:blogger.com,1999:blog-19739956.post-778476483715902259
blogger_orig_url: http://theabellsix.blogspot.com/2011/02/engineering-or-humanities.html
---

I have a lot of thoughts about this <a href="http://www.dougwils.com/index.php?option=com_content&amp;view=article&amp;id=8408:like-a-slide-rule-in-a-salvador-dali-painting&amp;catid=39:education">post</a> and, if I were a good blogger, would write them down. But, I am not a good blogger, so I will only quote a paragraph or two and say that, with regard to engineering and humanities, <a href="http://www.dougwils.com/">Wilson</a> is spot on.<br /><blockquote><blockquote>Here is the problem in a nutshell. When it comes to higher education, what do we do with our best and brightest? Overwhelmingly, Christian parents of high-achieving kids seek out some kind of technocratic program of study. They seek out the sciences and engineering. This is in part because Americans in general are pragmatic space shuttle builders, but there is an additional attraction here for Christians. What might it be?</blockquote><blockquote>We have to begin by comparing contemporary engineering to the contemporary humanities. Christians love the truth, and when you undertake a course of study in engineering, most of what you learn is true. The bridges have to stand, and the airplanes have to fly. The software needs to run. In most liberal arts programs, most of what you learn is false, with some of it being false and stupid. So there’s that.</blockquote><blockquote>In the old days, when the study of the liberal arts was Christian, there was a fixed standard that enabled you to navigate them. There is no problem with reading and studying error so long as you have a means of identifying it. You are an intelligent Christian participant in what Adler called the great conversation. The fact that the conversation extended over centuries does not mean that it turns out we are all saying the same thing. You need to know what Plato said in order to take issue. But when you are immersed in this world and all the standards of measurement look like a slide rule in a Salvador Dali painting, the only possible result is a nihilistic relativism.</blockquote></blockquote>&nbsp;Read the whole <a href="http://www.dougwils.com/index.php?option=com_content&amp;view=article&amp;id=8408:like-a-slide-rule-in-a-salvador-dali-painting&amp;catid=39:education">thing</a>.