---
layout: post
title: Books Completed in 2011
date: '2012-01-01T19:09:00.000-06:00'
author: Jabell
tags:
- Lists
- Books
modified_time: '2012-01-01T19:09:59.953-06:00'
blogger_id: tag:blogger.com,1999:blog-19739956.post-4293874767601308721
blogger_orig_url: http://theabellsix.blogspot.com/2012/01/books-completed-in-2011.html
---

Here is the list for 2011. My goal is a minimum of 12 books <i>completed</i> per year, or an average of one per month. If I start a book in one year, and finish it in the next, it counts in the year it was completed. My sights are set low, but the goal is attainable. (Obviously, I am not shooting for stars and hoping for the moon: I am settling for clouds.)<div><br /></div><div>I try to read some books that my kids are reading, because I love to read young adult fiction, and I love to read what my kids are reading, as it makes for great conversations. I prefer novels, as I have been reading fiction since my earliest memories of reading. I also enjoy reading essays and theology. The problem with the latter is that I am very slow. Oh well. Novels help me attain my yearly goal.</div><div><br /></div><div>I also previously posted on books read in&nbsp;<a href="http://theabellsix.blogspot.com/2011/01/books-completed-in-2010.html">2010</a>&nbsp;and&nbsp;<a href="http://theabellsix.blogspot.com/2010/12/books-read.html">2008/2009</a>.<div><br /></div><div><div><i>Wayfaring: Essays Pleasant and Unpleasant</i>, by&nbsp;Alan Jacobs</div><div><i>The Lightning Thief: Percy Jackson and the Olympians</i>, Book One, by&nbsp;Rick Riordan</div><div><i>The Rise and Fall of Mount Majestic</i>, by&nbsp;Jennifer Trafton</div><div><i>The Sea of Monsters: Percy Jackson and the Olympians</i>, Book Two, by&nbsp;Rick Riordan</div><div><i>The Titan's Curse: Percy Jackson and the Olympians</i>, Book Three, by&nbsp;Rick Riordan</div><div><i>The Battle of the Labyrinth: Percy Jackson and the Olympians</i>, Book Four, by&nbsp;Rick Riordan</div><div><i>The Last Olympian: Percy Jackson and the Olympians</i>, Book Five, by&nbsp;Rick Riordan</div><div><i>The Lost Hero: Heroes of Olympus</i>, Book One, by&nbsp;Rick Riordan</div><div><i>The Fiddler’s Gun</i>, by&nbsp;A. S. Peterson</div><div><i>The Fiddler’s Green</i>, by&nbsp;A. S. Peterson</div><div><i>The Elements of Style</i>, by&nbsp;William Strunk, Jr. &amp; E. B. White</div><div><i>Treasure Island</i>, by&nbsp;Robert Louis Stevenson</div><div><i>The Dragon's Tooth</i>, by&nbsp;Nathan D. Wilson</div><div><i>Holes</i>, by&nbsp;Louis Sachar</div><div><i>The Monster in the Hollows: The Wingfeather Saga</i>, Book Three, by&nbsp;Andrew Peterson</div><div><i>The Son of Neptune: Heroes of Olympus</i>, Book Two, by&nbsp;Rick Riordan</div><div><i>Crazy U: One Dad’s Crash Course in Getting His Kid into College</i>, by&nbsp;Andrew Ferguson</div><div><i>Living in God's Two Kingdoms: A Biblical Vision for Christianity and Culture</i>, by&nbsp;David VanDrunen</div></div></div>