---
layout: post
title: Books Completed in 2012
date: '2013-01-01T11:39:00.000-06:00'
author: Jabell
tags:
- Lists
- Books
modified_time: '2013-01-11T12:04:44.602-06:00'
blogger_id: tag:blogger.com,1999:blog-19739956.post-8237270015301788968
blogger_orig_url: http://theabellsix.blogspot.com/2013/01/books-completed-in-2012.html
---

Here is the list of books I completed during the calendar year 2012. My goal is a minimum of 12 books completed per year, or an average of one per month. If I start a book in one year, and finish it in the next, it counts in the year it was completed. My sights are set low, but this way the goal is attainable. (Obviously, I am not shooting for stars and hoping for the moon: I am settling for clouds.)<div><br /></div><div>Caveats: 2012 was a difficult year, and I had great difficulty focusing on anything deep, difficult, or serious outside of work, which accounts for the proliferation of novels on this year’s list. Yes, I do feel a bit sheepish that the novels I read were more on the side of escapist fiction than classic literature, but I think G.K. Chesterton had it right <a href="http://theabellsix.blogspot.com/2011/08/hero-among-dragons.html">here</a>, <a href="http://theabellsix.blogspot.com/2011/09/slay-dragon.html">here</a>, and <a href="http://theabellsix.blogspot.com/2011/03/what-do-we-choose-to-imagine.html">here</a>.</div><div><br /></div><div>I also previously posted on books read in <a href="http://theabellsix.blogspot.com/2012/01/books-completed-in-2011.html">2011</a>, <a href="http://theabellsix.blogspot.com/2011/01/books-completed-in-2010.html">2010</a>, and <a href="http://theabellsix.blogspot.com/2010/12/books-read.html">2008/2009</a>.<br /><br /><i>Cover Her Face,</i> by P. D. James<br /><i>The Hunger Games</i>, by Suzanne Collins<br /><i>Catching Fire</i>, by Suzanne Collins<br /><i>Mockingjay</i>, by Suzanne Collins<br /><i>The Summer Tree</i>, by Guy Gavriel Kay<br /><i>The Wandering Fire</i>, by Guy Gavriel Kay<br /><i>Where the Sidewalk Ends: The Poems and Drawings of Shel Silverstein</i>, by Shel Silverstein<br /><i>Writing Magic: Creating Stories That Fly</i>, by Gail Carson Levine<br /><i>Harry Potter and the Sorcerer's Stone</i>, by J. K. Rowling<br /><i>Harry Potter and the Chamber of Secrets</i>, by J. K. Rowling<br /><i>Graphic Design: The New Basics</i>, by Ellen Lupton and Jennifer Cole Phillips<br /><i>The Chronicles of Amber, Volume 1</i>, by Roger Zelazny<br /><i>The Chronicles of Amber, Volume 2</i>, by Roger Zelazny<br /><i>Hannah Coulter</i>, by Wendell Berry<br /><i>The Bourne Identity</i>, by Robert Ludlum<br /><i>The Bourne Supremacy</i>, by Robert Ludlum<br /><i>The Bourne Ultimatum</i>, by Robert Ludlum<br /><i>100 Cupboards</i>, by N. D. Wilson<br /><i>Dandelion Fire</i>, by N. D. Wilson</div><div><br /></div>